---
version: 2.1
jobs:
  build:
    working_directory: ~/every-shillings-android
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run:
          name: Install Kotlin
          command: |
            curl -s https://get.sdkman.io | bash
            source "$ANDROID_HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin


      - run:
          name: Set up Android environment
          command: |
            export ANDROID_HOME=~/Android/Sdk
            export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH


      - run:
          name: Build and test
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
            ./gradlew build test
workflows:
  build_and_test:
    jobs:
      - build