version: 2.1

orbs:
  android: circleci/android@1.2.0

jobs:
  build:
    executor: android/default
    steps:
      - checkout
      - android/setup:
          components: "build-tools-29.0.3,platforms;android-29"
      - run: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/outputs/
          destination: app-outputs

  test:
    executor: android/default
    steps:
      - checkout
      - android/setup:
          components: "build-tools-29.0.3,platforms;android-29"
      - run: ./gradlew assembleDebug
      - run: ./gradlew testDebug

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
