# ---
# version: 2.1
# jobs:
#   build:
#     working_directory: ~/every-shillings-android
#     docker:
#       - image: circleci/openjdk:11-jdk-buster
#     steps:
#       - checkout
#       - run:
#           name: Install Kotlin
#           command: |
#             curl -s https://get.sdkman.io | bash
#             source "$ANDROID_HOME/.sdkman/bin/sdkman-init.sh"
#             sdk install kotlin


#       - run:
#           name: Set up Android environment
#           command: |
#             export ANDROID_HOME=~/Android/Sdk
#             export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH


#       - run:
#           name: Build and test
#           command: |
#             sudo chmod +x ./gradlew
#             ./gradlew androidDependencies
#             ./gradlew build test
# workflows:
#   build_and_test:
#     jobs:
#       - build


#
# Build configuration for Circle CI
#

general:
    artifacts:
        - /home/ubuntu/every-shillings-android/app/build/outputs/apk/

machine:
    environment:
        ANDROID_HOME: /usr/local/android-sdk-linux

dependencies:
    override:
        - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-21.1.2,android-21,extra-google-m2repository,extra-google-google_play_services,extra-android-support
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies

test:
    override:
        - (./gradlew assemble):
            timeout: 360