version: 2.1

jobs:
  build:
    working_directory: ~/every-shillings-android
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run:
          name: Set up Kotlin
          command: |
             sudo apt-get update
            sudo apt-get install -y curl
            echo 'export PATH="/usr/local/kotlin/bin:$PATH"' >> $BASH_ENV
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin

      - run:
          name: Build and test
          command: |
            ./gradlew build test

workflows:
  build_and_test:
    jobs:
      - build
