version: 2.1

jobs:
  build:
    working_directory: ~/every-shillings-backend
    docker:
      - image: circleci/openjdk:11-jdk-buster
    steps:
      - checkout
      - run:
          name: Set up JDK and Kotlin
          command: |
            echo 'export PATH="/usr/local/kotlin/bin:$PATH"' >> $BASH_ENV
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install kotlin
            sdk use kotlin
      - run:
          name: Build and test
          command: |
            sudo chmod +x ./gradlew
            ./gradlew androidDependencies
            ./gradlew build test

workflows:
  build_and_test:
    jobs:
      - build
